package types

const (
	SERVER_HTTP      = byte(1)
	SERVER_WEBSOCKET = byte(2)

	SERVER_HTTP_KEY      = "SERVER_KEY/1"
	SERVER_WEBSOCKET_KEY = "SERVER_KEY/2"
	SERVER_NAME_KEY      = "SERVER_NAME_KEY/0"
)
